export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';

export const REQUEST_COUNTRIES_PENDING = 'REQUEST_COUNTRIES_PENDING';
export const REQUEST_COUNTRIES_SUCCESS = 'REQUEST_COUNTRIES_SUCCESS';
export const REQUEST_COUNTRIES_FAILED = 'REQUEST_COUNTRIES_FAILED';

export const REQUEST_COMPETITIONS_PENDING = 'REQUEST_COMPETITIONS_PENDING';
export const REQUEST_COMPETITIONS_SUCCESS = 'REQUEST_COMPETITIONS_SUCCESS';
export const REQUEST_COMPETITIONS_FAILED = 'REQUEST_COMPETITIONS_FAILED';